name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: ubuntu-24.04-arm
            target-platform: linux-aarch64
          - os: macos-latest
            target-platform: osx-64
          - os: macos-latest
            target-platform: osx-arm64
          - os: windows-latest
            target-platform: win-64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.37
        with:
          recipe-path: recipe/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }}
          artifact-name: package-${{ matrix.target-platform }}
